initial import from CF
AnacondaRecipes/autograd-feedstock pull request #1
Opened 2021-10-06 20:21 UTC by dkomisar

2021-10-07 06:17 UTC, katietz requested changes
By looking at setup.py I see that it depends on install_requires=['numpy>=1.12', 'future>=0.15.2'],
So please adjust numpy dependency

2021-10-11 12:36 UTC, katietz approved these changes

2021-10-11 12:36 UTC, katietz commented on recipe/meta.yaml
> +    - numpy >=1.12
Sure about 1.12? Shouldn't we go directly with 1.16 (which is our lowest numpy variant here anyway for most targets?)

2021-10-11 12:39 UTC, dkomisar commented on recipe/meta.yaml
> +    - numpy >=1.12
We could, I was adjusting it to use 1.12 from your other comment. If we don't have anything less than 1.16 guess that makes no difference but I don't see why we'd want it to differ from the upstream versions if we get the same result.

2021-10-11 14:57 UTC, merged